[features]
seeds = false
skip-lint = false
[programs.devnet]
cutils = "14cpGE5kYBuZY9Pf6q9auoN5qj35H4WkYsQ4Cv4PAAV2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
